---
title: "Final Projects"
---

[EPISODE 1: Puzzles and Games](https://smith.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=edbbaf2e-fb9a-4cf8-a444-aba9003a8c31)

 - Ali, Emily K., Annika, and Rocio:	[Soduku and Graph Theory](https://medium.com/smith-hcv/can-you-effectively-solve-sudoku-290d9b6fd77c)
 - Kendra:	Go is PSPACE-hard
 - Naomi:	[Computational complexity of Chess](https://medium.com/smith-hcv/computational-complexity-of-a-game-of-nxn-chess-e000f2070d8a)
 - Abby:	[Nonograms: Combinatorial questions and algorithms](https://medium.com/smith-hcv/solving-hard-instances-of-nonograms-35c68e4a26df)
 - Sasha and Ileanna:	[Tetris is Hard, Even to Approximate](https://medium.com/smith-hcv/np-completeness-of-tetris-ebbb24c7ba7a)
 - Sophie: [Minesweeper is NP-Complete](https://medium.com/smith-hcv/minesweeper-is-np-complete-47e37895cc52)
 - Tess:	[The Computational Complexity of Portal and Other 3D Video Games](https://medium.com/smith-hcv/the-computational-complexity-of-portal-and-other-3d-video-games-bd747963e1a9)

<hr>
[EPISODE 2: Math and Technology](https://smith.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=38902a36-001a-42ff-9471-abaa003cda1b)

 - Tzu-Chin (Laetitia) and Eleni:	[What are Quantum Computers, how do they work and where will we use them?](https://medium.com/what-are-quantum-computers-and-why-should-you-care/what-are-quantum-computers-and-why-should-you-ca-7ab5f5cfb0f7)
 - Sivan:	[Pollard's Rho Algorithm for Prime Factorization](https://medium.com/smith-hcv/pollards-rho-algorithm-for-prime-factorization-9002bf71d281)
 - Lucy:	[New Directions in Cryptography (Diffie-Hellman Key Exchange)](https://medium.com/smith-hcv/the-diffie-hellman-public-key-exchange-373a25c1a055)
 - Chenhui (Ivy), Helena, and Zihan:	[Computational complexity of convex hull algorithms](https://medium.com/smith-hcv/convex-hull-algorithms-in-2d-976803538452)
 - Jack:	[Different Problems, Common Threads: Computing the Difficulty of Mathematical Problems](https://medium.com/smith-hcv/reverse-mathematics-8f407affd8a1)
 - Phuong:	[Quantum finite automata](https://medium.com/smith-hcv/quantum-finite-automata-523157390faf)
 - Ananda and Sunshine:	[Algorithmic complexity and Randomness](https://medium.com/smith-hcv/randomness-information-theory-and-kolmogorov-complexity-6471e873bcd7)

<hr>
[EPISODE 3: Language, Music, and Thinking](https://smith.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=9997e90e-ca62-4a81-91f0-abad0029e81f)

 - Kaia: 	The Zodiac Killer Ciphers
 - Ellen:	[Natural Languages and Context-Free Languages](https://medium.com/smith-hcv/natural-languages-and-context-free-languages-23ffd3a0f04e)
 - Elise:	[A Practical Approach to Language Complexity: A Wikipedia Case Study](https://medium.com/smith-hcv/the-complexity-of-natural-language-the-recognition-problem-47c33617aa9)
 - Rebecca:	[Recursion in Pragmatics](https://medium.com/smith-hcv/250-final-project-recursion-in-pragmatics-7b57ad6e79f0)
 - Jenna:	[Computational Cognitive Modeling](https://medium.com/smith-hcv/an-overview-of-clarion-a-general-purpose-cognitive-model-e09460cd02bb)
 - Michele:	[Computational complexity of arranging music](https://medium.com/smith-hcv/music-arrangement-is-computationally-hard-8f5e231faaba)

<hr>
[EPISODE 4: More Puzzles, Games, and History]()

 - Isabel:	[Computer Go: what AlphaGo meant for AI](https://medium.com/smith-hcv/the-last-game-frontier-why-alphagos-2015-defeat-of-lee-sedol-mattered-b0276ada1ef1)
 - Syrine:	[Computational complexity of checkers](https://medium.com/smith-hcv/computational-complexity-of-checkers-d62fa4cc2d8c)
 - Sakina, Maha, Eileen, and Neamat:	[P-Space Hardness of Super Mario Brothers](https://medium.com/smith-hcv/super-mario-bros-is-harder-easier-than-we-thought-2d2c31f79bbb)
 - Sophia:	[Classic Nintendo Games are (Computationally) Hard](https://medium.com/smith-hcv/how-hard-is-pokemon-2343fdcfc75f)
 - Fay: Cryptography
 - Maggie:	[Cracking the Enigma](https://medium.com/smith-hcv/cracking-the-enigma-9e37e0fd8ca0)
 - Nikki:	Computational Complexity of the Enigma Machine

<hr>
[EPISODE 5: The Grand Finale]()

 - Sarah:	[A Gentle Introduction to Computational Complexity Through an Examination of Noodle Making](https://medium.com/smith-hcv/these-noodles-sure-are-complex-734145e84729)
 - Belen:	[Job shop problem complexity](https://medium.com/smith-hcv/the-job-shop-scheduling-problem-25afdaa8bc65)
 - Mariem:	[Motion Planning and PSPACE-completeness](https://medium.com/smith-hcv/presentation-of-the-computational-complexity-of-motion-planning-10267bc5904b)
 - Katie:	[Art Gallery Problem](https://medium.com/smith-hcv/the-art-gallery-problem-b162e840408f)
 - Anushree:	[Art Gallery Problem](https://medium.com/smith-hcv/the-art-gallery-problem-49b776cd786)
 - Arris, Denise, and Alicia:	[Art Gallery Problem](https://medium.com/smith-hcv/chvatals-art-gallery-theorem-f1911970b570)
 - You Jeen:	[Computational complexity of the Ray Tracing Problem](https://medium.com/smith-hcv/computational-complexity-of-ray-tracing-1db936e6aba4)

<!--<hr>
Want more? Check out the projects from [2018](projects-2018.html) and [2019](projects-2019.html).-->