---
title: "Schedule"
---
The following schedule is subject to change at any time. **NOTE:** This schedule was last updated on 18 March 2020 to account adjust for disruptions caused by COVID-19. It will continue to evolve in the coming weeks.


<style>
.two-axis-table tr:nth-child(15),
.two-axis-table tr:nth-child(16),
.two-axis-table tr:nth-child(17),
.two-axis-table tr:nth-child(18) {
  background: lightgrey;
}
.two-axis-table body {
  padding: 1rem;
}
</style>

<div class="ox-hugo-table two-axis-table">
| **Date** | **Topic**  | **Scribes** |  **Assignment** |
| ---------|------------|-------------|-----------------|
| 1/28/20  | [Introduction](https://moodle.smith.edu/mod/resource/view.php?id=525927) |||
| 1/30/20  | [Logic and Proofs](https://moodle.smith.edu/mod/resource/view.php?id=527937) |T. Huang and E. Partakki||
| 2/4/20   | [Regular languages and expressions](https://moodle.smith.edu/mod/resource/view.php?id=529716) |S. Nachum and K. Cormier||
| 2/6/20   | [Finite Automata (DFAs and NFAs)](https://moodle.smith.edu/mod/resource/view.php?id=530363) |Y.J. Ha and S. Crane|A1 due|
| 2/11/20  | [DFAs, NFAs and Regular Expressions](https://moodle.smith.edu/mod/resource/view.php?id=531687) |R. Jaime and M. Awaisi||
| 2/13/20  | [Non-regular languages, pumping lemma](https://moodle.smith.edu/mod/resource/view.php?id=532546) |L. Groves and A. Montoly|A2 due|
| 2/18/20  | [Turing Machines](https://moodle.smith.edu/mod/resource/view.php?id=533515) |S. Matoussi and C.M. Perez||
| 2/20/20  | [Decidability](https://moodle.smith.edu/mod/resource/view.php?id=534089) |B. Meji and A. Eshghi|A3 due|
| 2/25/20  | [More on decidability](https://moodle.smith.edu/mod/resource/view.php?id=535106) |E. Dong and F. Adan||
| 2/27/20  | [Undecidable problems](https://moodle.smith.edu/mod/resource/view.php?id=536118) |T. Goldman and A. Goswami|A4 due|
| 3/3/20   | [Enumerability](https://moodle.smith.edu/mod/resource/view.php?id=537077) |E. Kim and M. Snoussi||
| 3/5/20   | [Midterm Review](https://moodle.smith.edu/mod/resource/view.php?id=537520) |I. Monsanto|A5 due|
| 3/10/20  | [Context-free languages and Push-down Automata pt.1](https://moodle.smith.edu/mod/resource/view.php?id=538372) |||
| 3/12/20  | [Context-free languages and Push-down Automata pt.2](https://moodle.smith.edu/mod/resource/view.php?id=538834)|Z. Miao and C. Jia| Exam 1 Due Friday |
| 3/17/20  |  |||
| 3/19/20  | |SPRING||
| 3/24/20  | |BREAK||
| 3/26/20  |  |||
| 3/31/20  | [More practice with reductions](https://smith.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=5c4036f9-374a-4324-af03-ab8e00cf4730) |D. Nava, A. Moise, M. Phan||
| 4/2/20   | [Mapping reductions](https://smith.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=aa00dbf7-ed57-4b43-b8ab-ab90005d34bd) |R. Warholic and Y. Shangguan||
| 4/7/20   | [Rice's Theorem](https://smith.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=8e6ecb70-69ce-455b-89a1-ab9500420703) |E. Schatzki-McCain||
| 4/9/20  | [Computational complexity](https://smith.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=d35bd38c-9dff-4d8f-a9ea-ab9800643af8) ||A6 due|
| 4/14/20  | [Application: introduction to cryptography](https://smith.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=359b903f-d657-4093-bd41-ab9d00351f4f) |S. Ali||
| 4/16/20  | ~~NP-completeness~~ (delayed to next week) ||A7 due|
| 4/21/20  | NP-completeness |||
| 4/23/20  | Semester Review ||A8 due|
| 4/28/20   | Student Presentations |||
| 4/30/20   | Student Presentations ||Final Project Post Due|
</div>
